const navLinks= document.querySelectorAll("nav-links li")
const mobileLinks= document.querySelectorAll("mobile-links li")
const menuBtn= document .querySelector(".mobile-menu-btn")
const mobileMenu= document .querySelector(".mobile-menu")
const overFlow= document .querySelector(".overflow")